#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — maf → ChatGPT app over the OpenAI Secure MCP Tunnel (docs/CHATGPT.md).
# Secrets are read hidden, written only to ~/.config/maf/*.env (0600), never echoed.
# ──────────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAF="${MAF:-$REPO_ROOT/.venv/bin/maf}"
CONFIG_DIR="$HOME/.config/maf"
TUNNEL_ENV="$CONFIG_DIR/tunnel.env"
MAF_ENV="$CONFIG_DIR/maf.env"
MAF_CONFIG_FILE="${MAF_CONFIG:-$CONFIG_DIR/config.yaml}"   # re-read from the unit after stage 1 (unit_config)
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
TC="$HOME/.local/bin/tunnel-client"
MAX_TRIES=3

die() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2; exit 1; }
ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

[[ -t 0 || -n "${WIZARD_ALLOW_NONTTY:-}" ]] || die "run this wizard in a terminal (it asks questions)"
[[ -x "$MAF" ]] || die "maf not found at $MAF (set MAF=/path/to/maf)"

# The words of a unit's ExecStart, with the %h (home) and %t (runtime directory) specifiers expanded.
exec_words() {
  local line
  line=$(grep -E '^ExecStart=' "$UNIT_DIR/$1" 2>/dev/null | head -n 1) || return 1
  line=${line#ExecStart=}
  line=${line//%h/$HOME}
  line=${line//%t/$RUNTIME_DIR}
  local -a words
  read -r -a words <<< "$line"
  printf '%s\n' "${words[@]}"
}

# The flags maf-tunnel.service passes to `tunnel-client run`, so doctor checks exactly what the unit runs.
unit_flags() {
  exec_words maf-tunnel.service | tail -n +3
}

# unit_option --NAME — the value maf-mcp.service passes to `maf serve --NAME`, or nothing.
unit_option() {
  local prev="" word
  while read -r word; do
    [[ "$prev" == "$1" ]] && { printf '%s' "$word"; return; }
    prev="$word"
  done < <(exec_words maf-mcp.service)
}

# The config file maf-mcp.service reads: its --config, else maf's default. The Origin fix (stage 9) must edit that one.
unit_config() {
  local config
  config="$(unit_option --config)"
  printf '%s' "${config:-$CONFIG_DIR/config.yaml}"
}

# Settings sources for `maf chatgpt setup`: the installed unit's --config/--vault/--workspaces, MAF_BUDGET_USD and
# XDG_DATA_HOME (an installed maf's data directory), unless this shell sets the matching variable. setup refuses to drop
# a source the unit has.
SETUP_ARGS=()
setup_sources() {
  local option variable value
  SETUP_ARGS=()
  for option in config vault workspaces; do
    variable="MAF_${option^^}"
    value="$(unit_option "--$option")"
    [[ -z "${!variable:-}" && -n "$value" ]] && SETUP_ARGS+=("--$option" "$value")
  done
  for variable in MAF_BUDGET_USD XDG_DATA_HOME; do
    value="$(grep -oE "^Environment=$variable=[^ ]+" "$UNIT_DIR/maf-mcp.service" 2>/dev/null | cut -d= -f3- || true)"
    if [[ -z "${!variable:-}" && -n "$value" ]]; then export "$variable=$value"; fi
  done
  return 0
}

# checksum FILE — to notice whether a stage changed a file (empty for a missing file).
checksum() { [[ -f "$1" ]] && sha256sum "$1" | cut -d' ' -f1 || true; }

health_addr() {
  local addr
  addr=$(grep -oE -- '--health\.listen-addr[= ][^ ]+' "$UNIT_DIR/maf-tunnel.service" 2>/dev/null | head -n 1) || true
  addr=${addr#--health.listen-addr}; addr=${addr#[= ]}
  printf '%s' "${addr:-127.0.0.1:8766}"
}

# run_tc ARGS... — tunnel-client with only tunnel.env's credentials: tunnel-client falls back to OPENAI_API_KEY when
# CONTROL_PLANE_API_KEY is unset, and this shell probably exports your provider keys.
run_tc() {
  ( unset OPENAI_API_KEY OPENAI_ADMIN_KEY GEMINI_API_KEY GOOGLE_API_KEY ANTHROPIC_API_KEY CONTROL_PLANE_API_KEY \
          CONTROL_PLANE_TUNNEL_ID
    set -a; . "$TUNNEL_ENV"; set +a
    exec "$TC" "$@" )
}

# tc_nokeys ARGS... — tunnel-client without any API key in its environment (health, version).
tc_nokeys() {
  env -u OPENAI_API_KEY -u OPENAI_ADMIN_KEY -u GEMINI_API_KEY -u GOOGLE_API_KEY -u ANTHROPIC_API_KEY \
      -u CONTROL_PLANE_API_KEY "$TC" "$@"
}

private() { chmod 600 "$1"; }

TOTAL_STAGES=11

banner "maf → ChatGPT: Secure MCP Tunnel setup"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Install tunnel-client and the systemd user units"
say "This installs OpenAI's tunnel-client (pinned v0.0.15, SHA-256 verified) into ~/.local/bin, then writes"
say "maf-mcp.service + maf-tunnel.service to $UNIT_DIR and 0600 env templates to $CONFIG_DIR."
note "Both steps are idempotent: re-running them keeps a verified binary and never overwrites a filled-in env file."
if [[ -x "$TC" ]] && confirm "tunnel-client is already at $TC. Re-check it with the installer anyway?"; then
  "$REPO_ROOT/scripts/install-tunnel-client.sh"
elif [[ ! -x "$TC" ]]; then
  confirm "Download and install tunnel-client now?" || die "tunnel-client is required; run scripts/install-tunnel-client.sh"
  "$REPO_ROOT/scripts/install-tunnel-client.sh"
fi
confirm "Run 'maf chatgpt setup' (install the units, daemon-reload)?" || die "the units are required: maf chatgpt setup"
MCP_UNIT_BEFORE="$(checksum "$UNIT_DIR/maf-mcp.service")"
setup_sources
"$MAF" ${SETUP_ARGS[@]+"${SETUP_ARGS[@]}"} chatgpt setup
MCP_UNIT_CHANGED=0
[[ "$(checksum "$UNIT_DIR/maf-mcp.service")" == "$MCP_UNIT_BEFORE" ]] || MCP_UNIT_CHANGED=1
MAF_CONFIG_FILE="$(unit_config)"
[[ -d "$CONFIG_DIR" ]] || mkdir -p -m 700 "$CONFIG_DIR"
pause "Press Enter to continue"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "OpenAI Platform: tunnel permissions"
say "Tunnels live in your OpenAI Platform organization (the one that belongs to your account)."
open_url "https://platform.openai.com/settings/organization/tunnels"
step "If the page shows the Tunnels list (maybe empty) with a 'Create tunnel' button, you are set: go on."
step "If it says 'Tunnels access required', an org owner or RBAC admin opens"
say  "    https://platform.openai.com/settings/organization/people/roles and grants you Tunnels:"
say  "    Read + Manage (to create the tunnel) and Read + Use (to run tunnel-client and pick it in ChatGPT)."
note "The sole owner of a personal org can grant these to themselves. New grants can take up to 30 minutes."
note "If Tunnels is not offered at all, your org may not have the rollout yet: stop here (docs/CHATGPT.md)."
pause "Press Enter once you can see the Tunnels page"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "OpenAI Platform: create the tunnel"
ENV_FILE="$TUNNEL_ENV"
step "On the Tunnels page click 'Create tunnel'."
step "Name: maf local   (Description optional)"
step "Organization IDs: your org id (org-..., shown under Settings → Organization → General)."
step "Workspace IDs: add your ChatGPT workspace id only if the dialog asks for one (Business/Enterprise)."
step "Click Create and copy the id: tunnel_ followed by 32 hex characters."
note "It takes 25-30 s before a new tunnel is active."
for (( try = 1; ; try++ )); do
  ask CONTROL_PLANE_TUNNEL_ID "Paste the tunnel id:"
  [[ "$CONTROL_PLANE_TUNNEL_ID" =~ ^tunnel_[0-9a-f]{32}$ ]] && break
  (( try < MAX_TRIES )) || die "that is not a tunnel id (tunnel_ + 32 lowercase hex); re-run the wizard"
  warn "expected tunnel_ + 32 lowercase hex characters, try again"
done
write_env CONTROL_PLANE_TUNNEL_ID "$CONTROL_PLANE_TUNNEL_ID"
private "$TUNNEL_ENV"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "OpenAI Platform: the tunnel runtime key"
ENV_FILE="$TUNNEL_ENV"
open_url "https://platform.openai.com/settings/organization/api-keys"
step "Click 'Create new secret key', name it 'maf tunnel runtime'."
step "Permissions: choose 'Restricted'. Set Tunnels to Read + Use; leave everything else at None."
step "Create, then copy the key (it is shown once)."
warn "Never use an 'All' key, your normal OPENAI_API_KEY or an admin key here: this key only runs the tunnel."
for (( try = 1; ; try++ )); do
  ask_secret CONTROL_PLANE_API_KEY "Paste the runtime key (hidden):"
  if [[ -z "$CONTROL_PLANE_API_KEY" || "$CONTROL_PLANE_API_KEY" =~ [[:space:]] ]]; then
    (( try < MAX_TRIES )) || die "no usable key entered; re-run the wizard"
    warn "empty or contains whitespace, try again"; continue
  fi
  if [[ -n "${OPENAI_API_KEY:-}" && "$CONTROL_PLANE_API_KEY" == "$OPENAI_API_KEY" ]]; then
    (( try < MAX_TRIES )) || die "that is your OPENAI_API_KEY; create a Restricted Tunnels key and re-run"
    warn "that is your OPENAI_API_KEY, not a Restricted Tunnels key; try again"; continue
  fi
  break
done
write_env CONTROL_PLANE_API_KEY "$CONTROL_PLANE_API_KEY"
private "$TUNNEL_ENV"
unset CONTROL_PLANE_API_KEY

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Provider keys for maf serve"
ENV_FILE="$MAF_ENV"
say "maf-mcp.service does not read ~/.bashrc, so it gets the three provider keys from $MAF_ENV (0600)."
note "Tip: keep the keys only there, not as export lines in ~/.bashrc, and have ~/.bashrc load them with"
note "  set -a; . ~/.config/maf/maf.env; set +a"
note "(Claude Code's sandbox cannot read ~/.config; it is also denied ~/.bashrc, but one copy is easier to keep safe)."
MAF_ENV_BEFORE="$(checksum "$MAF_ENV")"
for key in OPENAI_API_KEY GEMINI_API_KEY ANTHROPIC_API_KEY; do
  value="${!key:-}"
  if [[ -n "$value" ]] && confirm "Copy $key from this shell's environment into maf.env (not shown)?"; then
    write_env "$key" "$value"
  else
    ask_secret "$key" "Paste $key (hidden; Enter keeps the current value, empty skips):"
    if [[ -n "${!key:-}" ]]; then write_env "$key" "${!key}"; else SKIPPED+=("$key in $MAF_ENV"); warn "$key left empty: runs will fail until it is set"; fi
  fi
  private "$MAF_ENV"
done
unset value
MAF_ENV_CHANGED=0
[[ "$(checksum "$MAF_ENV")" == "$MAF_ENV_BEFORE" ]] || MAF_ENV_CHANGED=1

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Start maf serve and check the tunnel configuration"
say "Starts maf-mcp.service (maf serve on loopback), then runs 'tunnel-client doctor' with the exact flags of"
say "maf-tunnel.service, then asks the control plane about your tunnel with the runtime key."
confirm "Enable and start maf-mcp.service now?" || die "maf serve must run for the next steps"
systemctl --user enable maf-mcp.service
if systemctl --user is-active --quiet maf-mcp.service; then
  # A running unit keeps the environment and definition it started with; `start` would change nothing.
  if (( MAF_ENV_CHANGED || MCP_UNIT_CHANGED )); then
    warn "maf-mcp.service is already running with the old provider keys or unit; a restart applies the new ones."
    note "A restart stops an in-flight run at its next stage boundary (maf resume RUN_ID continues it)."
    if confirm "Restart maf-mcp.service now?"; then
      systemctl --user restart maf-mcp.service
    else
      SKIPPED+=("systemctl --user restart maf-mcp.service (until then maf runs with the old keys or unit)")
    fi
  else
    ok "maf-mcp.service is already running with the current keys and unit"
  fi
else
  systemctl --user start maf-mcp.service
fi
sleep 3
systemctl --user is-active --quiet maf-mcp.service || { journalctl --user -u maf-mcp.service -n 20 --no-pager; die "maf-mcp.service did not start"; }
ok "maf-mcp.service is active"
mapfile -t FLAGS < <(unit_flags) || true
(( ${#FLAGS[@]} )) || die "cannot read ExecStart from $UNIT_DIR/maf-tunnel.service (re-run maf chatgpt setup)"
expected_checks="mcp_server_reachable oauth_metadata"
if systemctl --user is-active --quiet maf-tunnel.service; then
  note "maf-tunnel.service is already running, so doctor's health_listener check may fail; that is expected."
  expected_checks+=" health_listener ui"
fi
doctor_rc=0
doctor_out="$(run_tc doctor "${FLAGS[@]}" --explain 2>&1)" || doctor_rc=$?
printf '%s\n' "$doctor_out" | sed 's/^/    /'
failed_checks="$(sed -n 's/^FAILED_CHECKS //p' <<< "$doctor_out" | tr ',' ' ')"
unexpected=""
for check in $failed_checks; do
  [[ " $expected_checks " == *" $check "* ]] || unexpected+=" $check"
done
if (( doctor_rc == 0 )); then
  ok "doctor: all checks passed"
elif [[ -n "$failed_checks" && -z "$unexpected" ]]; then
  # maf listens on a Unix socket (url=...,unix-socket=... in the unit); tunnel-client run dials it, but doctor
  # v0.0.15 probes the URL over TCP. maf's own check over the socket is in the status at the end of stage 7.
  note "doctor's failed checks ($failed_checks) are expected: maf listens on a Unix socket, which 'run' uses but"
  note "doctor v0.0.15 does not probe. 'maf chatgpt status' checks maf over the socket in the next stage."
else
  warn "doctor reported problems (above); fix them before going on"
fi
note "doctor is a local preflight: it does not prove the key works. That is the next check (network, read-only):"
if run_tc admin tunnels get "$(grep -E '^CONTROL_PLANE_TUNNEL_ID=' "$TUNNEL_ENV" | tail -n 1 | cut -d= -f2-)"; then
  ok "the runtime key can read the tunnel"
else
  warn "the control plane refused: check the key is Restricted with Tunnels Read + Use in the tunnel's org,"
  warn "that the tunnel id is right, and allow up to 30 minutes after a role change. Then re-run this wizard."
fi
pause "Press Enter to continue"

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Start the tunnel"
HEALTH="$(health_addr)"
confirm "Enable and (re)start maf-tunnel.service now?" || die "the tunnel must run for ChatGPT to reach maf"
systemctl --user enable maf-tunnel.service
# restart, not start: a running tunnel-client keeps the key it started with and retries a refused one forever. A
# tunnel restart never touches maf or its runs.
systemctl --user restart maf-tunnel.service
say "Waiting for a successful control-plane poll (up to 90 s)..."
ready=0
for _ in $(seq 1 30); do
  if tc_nokeys health --url "http://$HEALTH" --require-control-plane-poll >/dev/null 2>&1; then ready=1; break; fi
  sleep 3
done
if (( ready )); then ok "tunnel-client is polling the control plane"; else warn "no successful poll yet; see the status below"; fi
if [[ "$(loginctl show-user "$USER" --property=Linger --value 2>/dev/null || true)" != "yes" ]]; then
  note "Without linger, your user's systemd starts the units only once you log in, and stops them when you log out:"
  note "after a reboot ChatGPT cannot reach maf until you log in."
  if confirm "Start the units at boot without a login and keep them running after logout (loginctl enable-linger)?"; then
    loginctl enable-linger "$USER" && ok "linger enabled"
  else
    SKIPPED+=("loginctl enable-linger (without it the units start only at login and stop at logout)")
  fi
fi
"$MAF" chatgpt status --lines 5 || true
pause "Press Enter to continue"

# ── 8 ────────────────────────────────────────────────────────────────────
stage "ChatGPT: turn on Developer mode"
open_url "https://chatgpt.com/"
step "Profile menu → Settings → Security and login (older UIs: Apps & Connectors → Advanced settings)."
step "Turn on 'Developer mode' and accept the warning."
note "OpenAI's developer docs list Pro, Plus, Business, Enterprise and Edu (web). Some Help Center wording limits"
note "write tools to Business/Enterprise/Edu; if start_run is missing or blocked later, that is why."
note "In Business/Enterprise/Edu workspaces an admin must allow Developer mode first."
pause "Press Enter once Developer mode is on"

# ── 9 ────────────────────────────────────────────────────────────────────
stage "ChatGPT: create the MultiAgent app (Connection → Tunnel)"
TUNNEL_ID_SHOWN="$(grep -E '^CONTROL_PLANE_TUNNEL_ID=' "$TUNNEL_ENV" | tail -n 1 | cut -d= -f2-)"
open_url "https://chatgpt.com/plugins"
step "Click the + button (new app). Name: MultiAgent   Description: Start and inspect maf pipeline runs."
step "Connection: switch from 'Server URL' to 'Tunnel', then pick 'maf local' under Available tunnels,"
say  "    or paste the id: $TUNNEL_ID_SHOWN"
step "Authentication: No Authentication (maf is reachable only through your tunnel)."
step "Acknowledge the risk notice and click Create. ChatGPT now calls initialize + tools/list through the tunnel."
step "The app appears under Drafts; its page lists start_run, get_run_status, get_run_result, list_runs."
note "Labels may differ slightly from these (the UI changes); the Connection → Tunnel choice is the key part."
pause "Press Enter once the app is created (or if creation failed, to diagnose)"
origin="$(journalctl --user -u maf-mcp.service --since '-20 min' --no-pager -o cat 2>/dev/null \
          | grep -oE 'Invalid Origin header: [^ ]+' | tail -n 1 | sed 's/^Invalid Origin header: //' || true)"
if [[ -n "$origin" ]]; then
  warn "maf refused requests with 'Origin: $origin' (DNS-rebinding protection)."
  if [[ "$origin" =~ ^https://[a-z0-9.-]+$ ]] && confirm "Allow exactly this origin (mcp_allowed_origins in $MAF_CONFIG_FILE) and restart maf-mcp?"; then
    if [[ -f "$MAF_CONFIG_FILE" ]] && grep -qE '^mcp_allowed_origins:' "$MAF_CONFIG_FILE"; then
      SKIPPED+=("add \"$origin\" to mcp_allowed_origins in $MAF_CONFIG_FILE, then: systemctl --user restart maf-mcp.service")
      warn "$MAF_CONFIG_FILE already has mcp_allowed_origins: add \"$origin\" there by hand"
    else
      mkdir -p "$(dirname "$MAF_CONFIG_FILE")"
      if [[ -s "$MAF_CONFIG_FILE" && -n "$(tail -c 1 "$MAF_CONFIG_FILE")" ]]; then printf '\n' >> "$MAF_CONFIG_FILE"; fi
      printf 'mcp_allowed_origins: ["%s"]\n' "$origin" >> "$MAF_CONFIG_FILE"
      ok "added mcp_allowed_origins: [\"$origin\"] to $MAF_CONFIG_FILE"
      note "a restart stops an in-flight run at its next stage boundary (maf resume continues it)"
      systemctl --user restart maf-mcp.service && ok "maf-mcp.service restarted (maf-tunnel.service with it)"
      say "Now retry: in the app's settings click Refresh, or delete the draft and create it again."
    fi
  fi
else
  ok "no Origin rejections in maf's log"
fi
pause "Press Enter to continue"

# ── 10 ───────────────────────────────────────────────────────────────────
stage "Test from ChatGPT"
step "Open a new chat. In the composer: + → Developer mode → select MultiAgent."
step "Read-only test (no confirmation, no cost). Type:"
say  "    Use the MultiAgent app's list_runs tool to list my maf runs."
note "Expect a list (possibly empty). maf's journal shows the POST /mcp calls: journalctl --user -u maf-mcp -f"
step "Write test (spends real money, capped by budget_usd). Type:"
say  "    Use MultiAgent start_run with brief \"Write a 300-word plain-language note on what a tokamak is\" and budget_usd 3."
note "maf reserves each call's worst case, so budgets under about \$2 stop early (budget_exceeded); this one usually costs under \$1."
note "ChatGPT asks you to confirm start_run (it is a write tool); confirm. It returns a run_id at once."
step "Then: \"Check that run with get_run_status\" a few times, and \"get_run_result\" once it is completed."
note "Locally: $MAF list   /   $MAF status RUN_ID. A run takes minutes; each tool call must finish within"
note "ChatGPT's 1-minute limit, which is why start_run returns immediately and you poll."
pause "Press Enter when done (or if something failed, for troubleshooting)"

# ── 11 ───────────────────────────────────────────────────────────────────
stage "Troubleshooting and day-to-day"
say "Check everything:   $MAF chatgpt status"
say "Logs:               journalctl --user -u maf-mcp -u maf-tunnel -f"
say "Tunnel admin UI:    http://$(health_addr)/ui"
step "Tunnel not listed in ChatGPT: wait 30 s after creating it, check your Tunnels Read + Use role, paste the id."
step "Control-plane 401/403: key not Restricted Tunnels Read + Use, wrong org, or role still propagating (30 min)."
step "'Invalid Origin header' in maf's log: add exactly that origin to mcp_allowed_origins in $MAF_CONFIG_FILE."
step "After editing tunnel.env: systemctl --user restart maf-tunnel (a running tunnel keeps its old key; runs continue)."
step "After editing maf.env or maf's config: systemctl --user restart maf-mcp (restarts the tunnel too; an in-flight"
say  "    run stops at its next stage boundary, maf resume RUN_ID continues it)."
step "Tools changed after a maf update: app settings → Refresh. A new chat re-asks start_run confirmations."
step "Stopping maf waits for the running stage (up to 2 h): systemctl --user stop --no-block maf-mcp"
step "Start again after a stop: systemctl --user start maf-tunnel (it starts maf-mcp too; starting maf-mcp alone"
say  "    leaves the tunnel stopped)."
step "Details, security model and limits: docs/CHATGPT.md"
pause "Press Enter to finish"

ENV_FILE="$CONFIG_DIR/{tunnel,maf}.env"   # for the summary line: values went to both files
finish
note "secrets were written only to $TUNNEL_ENV and $MAF_ENV (mode 0600)"
